import { reducer, initialState } from '../context/reducer';
import { STALLS } from '../lib/data';
import { findStall, ST } from '../lib/helpers';

let s = initialState();
const assert = (cond: any, msg: string) => { if (!cond) { console.error('FAIL:', msg); process.exitCode = 1; } else console.log('ok:', msg); };

// tab switching
s = reducer(s, { type: 'SET_TAB', tab: 'explore' });
assert(s.tab === 'explore', 'tab switches to explore');

// cart add/remove
s = reducer(s, { type: 'ADD_TO_CART', sid: 's1', k: 0 });
s = reducer(s, { type: 'ADD_TO_CART', sid: 's1', k: 0 });
assert(s.cart.items[0] === 2, 'cart qty increments to 2');
s = reducer(s, { type: 'DEC_CART', k: 0 });
assert(s.cart.items[0] === 1, 'cart qty decrements to 1');

// cart clash with a different stall
s = reducer(s, { type: 'ADD_TO_CART', sid: 's2', k: 0 });
assert(s.sheet?.t === 'clash', 'adding from a different stall triggers clash sheet');
s = reducer(s, { type: 'CLEAR_CART_START', sid: 's2', k: 0 });
assert(s.cart.sid === 's2' && s.cart.items[0] === 1, 'starting new basket replaces cart');

// checkout -> place order
s = reducer(s, { type: 'ADD_TO_CART', sid: 's2', k: 1 });
const before = s.orders.length;
s = reducer(s, { type: 'PLACE_ORDER' });
assert(s.orders.length === before + 1, 'placing order adds to orders list');
assert(s.cart.sid === null, 'cart cleared after placing order');
assert(s.tab === 'orders', 'switches to Orders tab after placing');
const newOrderId = s.orders[0].id;
assert(s.orders[0].status === 0, 'new order starts at status 0');

// advance order through full lifecycle
for (let i = 1; i <= 6; i++) {
  s = reducer(s, { type: 'ADVANCE_ORDER', id: newOrderId });
}
assert(s.orders[0].status === 6, 'order reaches delivered status 6');
assert(!!s.orders[0].rider, 'rider assigned by stage 4');
assert(!!s.orders[0].otp, 'OTP generated by stage 4');

// decline flow
s = reducer(s, { type: 'ADD_TO_CART', sid: 's3', k: 0 });
s = reducer(s, { type: 'PLACE_ORDER' });
const declineId = s.orders[0].id;
s = reducer(s, { type: 'DECLINE_ORDER', id: declineId });
assert(s.orders[0].cancelled === true, 'declined order is marked cancelled');

// add-flow wizard
s = reducer(s, { type: 'START_FLOW' });
assert(s.addStage === 'flow' && !!s.draft, 'add flow starts with a fresh draft');
s = reducer(s, { type: 'DRAFT_SET', patch: { name: 'Test Stall' } });
s = reducer(s, { type: 'DRAFT_TOGGLE_FOOD', v: 'kachori' });
assert(s.draft!.name === 'Test Stall' && s.draft!.foods.includes('kachori'), 'draft basics set');
s = reducer(s, { type: 'FLOW_NEXT' });
assert(s.step === 1, 'wizard advances to step 1 (location)');
s = reducer(s, { type: 'DRAFT_APPLY_MAPS', ll: [26.92, 75.80], area: 'Amer Road' });
assert(s.draft!.area === 'Amer Road' && !!s.draft!.ll, 'google maps link sets area + coords');
s = reducer(s, { type: 'FLOW_GOTO', step: 2 });
s = reducer(s, { type: 'DRAFT_ADD_ITEM' });
s = reducer(s, { type: 'DRAFT_SET_ITEM', i: 0, patch: { n: 'Test Item', p: '30' } });
assert(s.draft!.items[0].n === 'Test Item', 'menu item set');
s = reducer(s, { type: 'FLOW_GOTO', step: 5 });
s = reducer(s, { type: 'DRAFT_SET', patch: { rating: 5, rec: true } });
const extraBefore = s.extraStalls.length;
s = reducer(s, { type: 'DRAFT_SUBMIT' });
assert(s.extraStalls.length === extraBefore + 1, 'submitting draft adds a new stall to extraStalls');
assert(s.addStage === 'done' && !!s.done, 'flow reaches done stage');
assert(s.points > 220, 'points increased after publishing');

// vendor mode
s = reducer(s, { type: 'VENDOR_ON' });
assert(s.vendor === true, 'vendor mode toggles on');
s = reducer(s, { type: 'VENDOR_TOGGLE_OPEN' });
const vs = ST(s.vsid, s.extraStalls, s.stallEdits)!;
assert(vs.open === false, 'vendor can close their stall');
s = reducer(s, { type: 'VENDOR_ADD_ITEM', n: 'New Item', p: 40 });
const vs2 = ST(s.vsid, s.extraStalls, s.stallEdits)!;
assert(vs2.items.some(i => i.n === 'New Item'), 'vendor can add a menu item');

// community: vote, poll, comments, rsvp
s = reducer(s, { type: 'VOTE', id: 't1', v: 'up' });
assert(s.votes['t1'] === 'up', 'thread upvote recorded');
s = reducer(s, { type: 'VOTE', id: 't1', v: 'up' });
assert(s.votes['t1'] === null, 'toggling same vote clears it');
s = reducer(s, { type: 'POLL_VOTE', id: 't1', i: 0 });
assert(s.pollPick['t1'] === 0, 'poll vote recorded');
s = reducer(s, { type: 'POLL_VOTE', id: 't1', i: 1 });
assert(s.pollPick['t1'] === 0, 'poll vote is one-time, second vote ignored');
s = reducer(s, { type: 'POST_COMMENT', tid: 't2', text: 'Great thread!' });
assert(s.commentDraft === '', 'comment draft clears after posting');
s = reducer(s, { type: 'RSVP', id: 't3' });
assert(s.toast?.includes('in'), 'RSVP toast shown');

// reels
s = reducer(s, { type: 'REEL_OPEN', idx: 0 });
assert(s.reelOpen === true && s.reelIdx === 0, 'reels open at index 0');
s = reducer(s, { type: 'REEL_LIKE', id: 'r1' });
assert(s.rxn['r1'] === 'like', 'reel like toggled');
s = reducer(s, { type: 'REEL_NEXT' });
assert(s.reelIdx === 1, 'reel advances to next');

// stories
s = reducer(s, { type: 'STORY_OPEN', i: 2 });
assert(s.storyOpen === true && s.storyIdx === 2, 'story viewer opens at group 2');
s = reducer(s, { type: 'STORY_NEXT' });
assert(s.storySlide === 1, 'story slide advances');

console.log('\\nAll reducer assertions executed.');
